name: Run Tests

on:
  pull_request:
    paths:
      - algpy_src/**
      - .github/workflows/run-tests.yml

  push:
    paths:
      - algpy_src/**
      - .github/workflows/run-tests.yml

defaults:
  run:
    working-directory: algpy_src
    shell: bash

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: algpy

      - name: Run tests
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml
        env:
          CI: true
        working-directory: algpy

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: junit/test-results.xml
